var COMPILED=!0,goog=goog||{};goog.global=this;goog.isDef=function(a){return void 0!==a};goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&goog.isDef(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};
goog.define=function(a,b){var c=b;COMPILED||(goog.global.CLOSURE_UNCOMPILED_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_UNCOMPILED_DEFINES,a)?c=goog.global.CLOSURE_UNCOMPILED_DEFINES[a]:goog.global.CLOSURE_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_DEFINES,a)&&(c=goog.global.CLOSURE_DEFINES[a]));goog.exportPath_(a,c)};goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;goog.STRICT_MODE_COMPATIBLE=!1;goog.DISALLOW_TEST_ONLY_CODE=COMPILED&&!goog.DEBUG;
goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING=!1;goog.provide=function(a){if(goog.isInModuleLoader_())throw Error("goog.provide can not be used within a goog.module.");if(!COMPILED&&goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');goog.constructNamespace_(a)};goog.constructNamespace_=function(a,b){if(!COMPILED){delete goog.implicitNamespaces_[a];for(var c=a;(c=c.substring(0,c.lastIndexOf(".")))&&!goog.getObjectByName(c);)goog.implicitNamespaces_[c]=!0}goog.exportPath_(a,b)};
goog.VALID_MODULE_RE_=/^[a-zA-Z_$][a-zA-Z0-9._$]*$/;
goog.module=function(a){if(!goog.isString(a)||!a||-1==a.search(goog.VALID_MODULE_RE_))throw Error("Invalid module identifier");if(!goog.isInModuleLoader_())throw Error("Module "+a+" has been loaded incorrectly. Note, modules cannot be loaded as normal scripts. They require some kind of pre-processing step. You're likely trying to load a module via a script tag or as a part of a concatenated bundle without rewriting the module. For more info see: https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide.");if(goog.moduleLoaderState_.moduleName)throw Error("goog.module may only be called once per module.");
goog.moduleLoaderState_.moduleName=a;if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a]}};goog.module.get=function(a){return goog.module.getInternal_(a)};goog.module.getInternal_=function(a){if(!COMPILED)return goog.isProvided_(a)?a in goog.loadedModules_?goog.loadedModules_[a]:goog.getObjectByName(a):null};goog.moduleLoaderState_=null;goog.isInModuleLoader_=function(){return null!=goog.moduleLoaderState_};
goog.module.declareLegacyNamespace=function(){if(!COMPILED&&!goog.isInModuleLoader_())throw Error("goog.module.declareLegacyNamespace must be called from within a goog.module");if(!COMPILED&&!goog.moduleLoaderState_.moduleName)throw Error("goog.module must be called prior to goog.module.declareLegacyNamespace.");goog.moduleLoaderState_.declareLegacyNamespace=!0};
goog.setTestOnly=function(a){if(goog.DISALLOW_TEST_ONLY_CODE)throw a=a||"",Error("Importing test-only code into non-debug environment"+(a?": "+a:"."));};goog.forwardDeclare=function(a){};COMPILED||(goog.isProvided_=function(a){return a in goog.loadedModules_||!goog.implicitNamespaces_[a]&&goog.isDefAndNotNull(goog.getObjectByName(a))},goog.implicitNamespaces_={"goog.module":!0});
goog.getObjectByName=function(a,b){for(var c=a.split("."),d=b||goog.global,f;f=c.shift();)if(goog.isDefAndNotNull(d[f]))d=d[f];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};
goog.addDependency=function(a,b,c,d){if(goog.DEPENDENCIES_ENABLED){var f;a=a.replace(/\\/g,"/");var e=goog.dependencies_;d&&"boolean"!==typeof d||(d=d?{module:"goog"}:{});for(var g=0;f=b[g];g++)e.nameToPath[f]=a,e.loadFlags[a]=d;for(d=0;b=c[d];d++)a in e.requires||(e.requires[a]={}),e.requires[a][b]=!0}};goog.ENABLE_DEBUG_LOADER=!0;goog.logToConsole_=function(a){goog.global.console&&goog.global.console.error(a)};
goog.require=function(a){if(!COMPILED){goog.ENABLE_DEBUG_LOADER&&goog.IS_OLD_IE_&&goog.maybeProcessDeferredDep_(a);if(goog.isProvided_(a)){if(goog.isInModuleLoader_())return goog.module.getInternal_(a)}else if(goog.ENABLE_DEBUG_LOADER){var b=goog.getPathFromDeps_(a);if(b)goog.writeScripts_(b);else throw a="goog.require could not find: "+a,goog.logToConsole_(a),Error(a);}return null}};goog.basePath="";goog.nullFunction=function(){};
goog.abstractMethod=function(){throw Error("unimplemented abstract method");};goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];goog.LOAD_MODULE_USING_EVAL=!0;goog.SEAL_MODULE_EXPORTS=goog.DEBUG;goog.loadedModules_={};goog.DEPENDENCIES_ENABLED=!COMPILED&&goog.ENABLE_DEBUG_LOADER;goog.TRANSPILE="detect";
goog.TRANSPILER="transpile.js";
goog.DEPENDENCIES_ENABLED&&(goog.dependencies_={loadFlags:{},nameToPath:{},requires:{},visited:{},written:{},deferred:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return null!=a&&"write"in a},goog.findBasePath_=function(){if(goog.isDef(goog.global.CLOSURE_BASE_PATH))goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("SCRIPT"),b=a.length-1;0<=b;--b){var c=a[b].src,d=c.lastIndexOf("?"),d=-1==d?c.length:d;if("base.js"==
c.substr(d-7,7)){goog.basePath=c.substr(0,d-7);break}}},goog.importScript_=function(a,b){(goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_)(a,b)&&(goog.dependencies_.written[a]=!0)},goog.IS_OLD_IE_=!(goog.global.atob||!goog.global.document||!goog.global.document.all),goog.importProcessedScript_=function(a,b,c){goog.importScript_("",'goog.retrieveAndExec_("'+a+'", '+b+", "+c+");")},goog.queuedModules_=[],goog.wrapModule_=function(a,b){return goog.LOAD_MODULE_USING_EVAL&&goog.isDef(goog.global.JSON)?
"goog.loadModule("+goog.global.JSON.stringify(b+"\n//# sourceURL="+a+"\n")+");":'goog.loadModule(function(exports) {"use strict";'+b+"\n;return exports});\n//# sourceURL="+a+"\n"},goog.loadQueuedModules_=function(){var a=goog.queuedModules_.length;if(0<a){var b=goog.queuedModules_;goog.queuedModules_=[];for(var c=0;c<a;c++)goog.maybeProcessDeferredPath_(b[c])}},goog.maybeProcessDeferredDep_=function(a){goog.isDeferredModule_(a)&&goog.allDepsAreAvailable_(a)&&(a=goog.getPathFromDeps_(a),goog.maybeProcessDeferredPath_(goog.basePath+
a))},goog.isDeferredModule_=function(a){var b=(a=goog.getPathFromDeps_(a))&&goog.dependencies_.loadFlags[a]||{};return a&&("goog"==b.module||goog.needsTranspile_(b.lang))?goog.basePath+a in goog.dependencies_.deferred:!1},goog.allDepsAreAvailable_=function(a){if((a=goog.getPathFromDeps_(a))&&a in goog.dependencies_.requires)for(var b in goog.dependencies_.requires[a])if(!goog.isProvided_(b)&&!goog.isDeferredModule_(b))return!1;return!0},goog.maybeProcessDeferredPath_=function(a){if(a in goog.dependencies_.deferred){var b=
goog.dependencies_.deferred[a];delete goog.dependencies_.deferred[a];goog.globalEval(b)}},goog.loadModuleFromUrl=function(a){goog.retrieveAndExec_(a,!0,!1)},goog.writeScriptSrcNode_=function(a){goog.global.document.write('<script type="text/javascript" src="'+a+'">\x3c/script>')},goog.appendScriptSrcNode_=function(a){var b=goog.global.document,c=b.createElement("script");c.type="text/javascript";c.src=a;c.defer=!1;c.async=!1;b.head.appendChild(c)},goog.writeScriptTag_=function(a,b){if(goog.inHtmlDocument_()){var c=
goog.global.document;if(!goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING&&"complete"==c.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}if(void 0===b)if(goog.IS_OLD_IE_){var d=" onreadystatechange='goog.onScriptLoad_(this, "+ ++goog.lastNonModuleScriptIndex_+")' ";c.write('<script type="text/javascript" src="'+a+'"'+d+">\x3c/script>")}else goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING?goog.appendScriptSrcNode_(a):goog.writeScriptSrcNode_(a);else c.write('<script type="text/javascript">'+
b+"\x3c/script>");return!0}return!1},goog.needsTranspile_=function(a){if("always"==goog.TRANSPILE)return!0;if("never"==goog.TRANSPILE)return!1;if(!goog.transpiledLanguages_){goog.transpiledLanguages_={es5:!0,es6:!0,"es6-impl":!0};try{goog.transpiledLanguages_.es5=eval("[1,].length!=1"),eval('(()=>{"use strict";class X{constructor(){if(new.target!=String)throw 1;this.x=42}}let q=Reflect.construct(X,[],String);if(q.x!=42||!(q instanceof String))throw 1;for(const a of[2,3]){if(a==2)continue;function f(z={a}){let a=0;return z.a}{function f(){return 0;}}return f()==3}})()')&&
(goog.transpiledLanguages_.es6=!1,goog.transpiledLanguages_["es6-impl"]=!1)}catch(b){}}return!!goog.transpiledLanguages_[a]},goog.transpiledLanguages_=null,goog.lastNonModuleScriptIndex_=0,goog.onScriptLoad_=function(a,b){"complete"==a.readyState&&goog.lastNonModuleScriptIndex_==b&&goog.loadQueuedModules_();return!0},goog.writeScripts_=function(a){function b(a){if(!(a in f.written||a in f.visited)){f.visited[a]=!0;if(a in f.requires)for(var e in f.requires[a])if(!goog.isProvided_(e))if(e in f.nameToPath)b(f.nameToPath[e]);
else throw Error("Undefined nameToPath for "+e);a in d||(d[a]=!0,c.push(a))}}var c=[],d={},f=goog.dependencies_;b(a);for(a=0;a<c.length;a++){var e=c[a];goog.dependencies_.written[e]=!0}var g=goog.moduleLoaderState_;goog.moduleLoaderState_=null;for(a=0;a<c.length;a++)if(e=c[a]){var h=f.loadFlags[e]||{},k=goog.needsTranspile_(h.lang);"goog"==h.module||k?goog.importProcessedScript_(goog.basePath+e,"goog"==h.module,k):goog.importScript_(goog.basePath+e)}else throw goog.moduleLoaderState_=g,Error("Undefined script input");
goog.moduleLoaderState_=g},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.loadModule=function(a){var b=goog.moduleLoaderState_;try{goog.moduleLoaderState_={moduleName:void 0,declareLegacyNamespace:!1};var c;if(goog.isFunction(a))c=a.call(void 0,{});else if(goog.isString(a))c=goog.loadModuleFromSource_.call(void 0,a);else throw Error("Invalid module definition");var d=goog.moduleLoaderState_.moduleName;if(!goog.isString(d)||!d)throw Error('Invalid module name "'+d+'"');goog.moduleLoaderState_.declareLegacyNamespace?goog.constructNamespace_(d,c):goog.SEAL_MODULE_EXPORTS&&
Object.seal&&goog.isObject(c)&&Object.seal(c);goog.loadedModules_[d]=c}finally{goog.moduleLoaderState_=b}};goog.loadModuleFromSource_=function(a){eval(a);return{}};goog.normalizePath_=function(a){a=a.split("/");for(var b=0;b<a.length;)"."==a[b]?a.splice(b,1):b&&".."==a[b]&&a[b-1]&&".."!=a[b-1]?a.splice(--b,2):b++;return a.join("/")};
goog.loadFileSync_=function(a){if(goog.global.CLOSURE_LOAD_FILE_SYNC)return goog.global.CLOSURE_LOAD_FILE_SYNC(a);try{var b=new goog.global.XMLHttpRequest;b.open("get",a,!1);b.send();return 0==b.status||200==b.status?b.responseText:null}catch(c){return null}};
goog.retrieveAndExec_=function(a,b,c){if(!COMPILED){var d=a;a=goog.normalizePath_(a);var f=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_,e=goog.loadFileSync_(a);if(null==e)throw Error('Load of "'+a+'" failed');c&&(e=goog.transpile_.call(goog.global,e,a));e=b?goog.wrapModule_(a,e):e+("\n//# sourceURL="+a);goog.IS_OLD_IE_?(goog.dependencies_.deferred[d]=e,goog.queuedModules_.push(d)):f(a,e)}};
goog.transpile_=function(a,b){var c=goog.global.$jscomp;c||(goog.global.$jscomp=c={});var d=c.transpile;if(!d){var f=goog.basePath+goog.TRANSPILER,e=goog.loadFileSync_(f);e&&(eval(e+"\n//# sourceURL="+f),c=goog.global.$jscomp,d=c.transpile)}d||(d=c.transpile=function(a,b){goog.logToConsole_(b+" requires transpilation but no transpiler was found.");return a});return d(a,b)};
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.hasUid=function(a){return!!a[goog.UID_PROPERTY_]};
goog.removeUid=function(a){null!==a&&"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=goog.cloneObject(a[c]);return b}return a};
goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
goog.bind=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval){if(null==goog.evalWorksForGlobals_)if(goog.global.eval("var _evalTest_ = 1;"),"undefined"!=typeof goog.global._evalTest_){try{delete goog.global._evalTest_}catch(d){}goog.evalWorksForGlobals_=!0}else goog.evalWorksForGlobals_=!1;if(goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("SCRIPT");c.type="text/javascript";c.defer=!1;c.appendChild(b.createTextNode(a));
b.body.appendChild(c);b.body.removeChild(c)}}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;
goog.getCssName=function(a,b){if("."==String(a).charAt(0))throw Error('className passed in goog.getCssName must not start with ".". You passed: '+a);var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split("-");for(var b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join("-")},d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?c:d:function(a){return a},d=b?a+"-"+d(b):d(a);return goog.global.CLOSURE_CSS_NAME_MAP_FN?goog.global.CLOSURE_CSS_NAME_MAP_FN(d):d};
goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){b&&(a=a.replace(/\{\$([^}]+)}/g,function(a,d){return null!=b&&d in b?b[d]:a}));return a};goog.getMsgWithFallback=function(a,b){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};
goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,e){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};
goog.base=function(a,b,c){var d=arguments.callee.caller;if(goog.STRICT_MODE_COMPATIBLE||goog.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(d.superClass_){for(var f=Array(arguments.length-1),e=1;e<arguments.length;e++)f[e-1]=arguments[e];return d.superClass_.constructor.apply(a,f)}f=Array(arguments.length-2);for(e=2;e<arguments.length;e++)f[e-2]=arguments[e];for(var e=!1,g=a.constructor;g;g=
g.superClass_&&g.superClass_.constructor)if(g.prototype[b]===d)e=!0;else if(e)return g.prototype[b].apply(a,f);if(a[b]===d)return a.constructor.prototype[b].apply(a,f);throw Error("goog.base called from a method of one name to a method of a different name");};goog.scope=function(a){if(goog.isInModuleLoader_())throw Error("goog.scope is not supported within a goog.module.");a.call(goog.global)};COMPILED||(goog.global.COMPILED=COMPILED);
goog.defineClass=function(a,b){var c=b.constructor,d=b.statics;c&&c!=Object.prototype.constructor||(c=function(){throw Error("cannot instantiate an interface (no constructor defined).");});c=goog.defineClass.createSealingConstructor_(c,a);a&&goog.inherits(c,a);delete b.constructor;delete b.statics;goog.defineClass.applyProperties_(c.prototype,b);null!=d&&(d instanceof Function?d(c):goog.defineClass.applyProperties_(c,d));return c};goog.defineClass.SEAL_CLASS_INSTANCES=goog.DEBUG;
goog.defineClass.createSealingConstructor_=function(a,b){if(!goog.defineClass.SEAL_CLASS_INSTANCES)return a;var c=!goog.defineClass.isUnsealable_(b),d=function(){var b=a.apply(this,arguments)||this;b[goog.UID_PROPERTY_]=b[goog.UID_PROPERTY_];this.constructor===d&&c&&Object.seal instanceof Function&&Object.seal(b);return b};return d};goog.defineClass.isUnsealable_=function(a){return a&&a.prototype&&a.prototype[goog.UNSEALABLE_CONSTRUCTOR_PROPERTY_]};goog.defineClass.OBJECT_PROTOTYPE_FIELDS_="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
goog.defineClass.applyProperties_=function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c]);for(var d=0;d<goog.defineClass.OBJECT_PROTOTYPE_FIELDS_.length;d++)c=goog.defineClass.OBJECT_PROTOTYPE_FIELDS_[d],Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};goog.tagUnsealableClass=function(a){!COMPILED&&goog.defineClass.SEAL_CLASS_INSTANCES&&(a.prototype[goog.UNSEALABLE_CONSTRUCTOR_PROPERTY_]=!0)};goog.UNSEALABLE_CONSTRUCTOR_PROPERTY_="goog_defineClass_legacy_unsealable";var com={jasonmayes:{}};com.jasonmayes.jama={};com.jasonmayes.jama.util={};com.jasonmayes.jama.util.Logger=function(a){void 0!==a&&(this.element_=a)};goog.exportSymbol("com.jasonmayes.jama.util.Logger",com.jasonmayes.jama.util.Logger);com.jasonmayes.jama.util.Logger.prototype.LogStates={LOG:"log",INFO:"info",WARNING:"warning",ERROR:"error",DEBUG:"debug"};goog.exportProperty(com.jasonmayes.jama.util.Logger.prototype,"LogStates",com.jasonmayes.jama.util.Logger.prototype.LogStates);
com.jasonmayes.jama.util.Logger.prototype.log=function(a,b,c){switch(b){case this.LogStates.LOG:c?console.log(a,c):console.log(a);break;case this.LogStates.DEBUG:c?console.debug(a,c):console.debug(a);break;case this.LogStates.INFO:c?console.info(a,c):console.info(a);break;case this.LogStates.WARNING:c?console.warn(a,c):console.warn(a);break;case this.LogStates.ERROR:c?console.error(a,c):console.error(a);break;default:c?console.log(a,c):console.log(a)}};
goog.exportProperty(com.jasonmayes.jama.util.Logger.prototype,"log",com.jasonmayes.jama.util.Logger.prototype.log);com.jasonmayes.jama.util.Logger.prototype.domLog=function(a,b,c){var d=document.createElement("p");d.textContent=a;d.setAttribute("class",b+" msg");void 0===c&&void 0!==this.element_?this.element_.appendChild(d):c.appendChild(d)};goog.exportProperty(com.jasonmayes.jama.util.Logger.prototype,"domLog",com.jasonmayes.jama.util.Logger.prototype.domLog);com.jasonmayes.jama.multimedia={};com.jasonmayes.jama.multimedia.audio={};
com.jasonmayes.jama.multimedia.audio.AudioPlayer=function(){function a(a){e.push(a);h(e.length-1);l=!1;c()}function b(a){d.log("Error loading sound",d.LogStates.ERROR);h(-1);l=!1;c()}function c(){if(0<m.length){var a=m.shift();com.jasonmayes.jama.multimedia.audio.AudioPlayer.loadSound(a.url,a.cback)}}var d=new com.jasonmayes.jama.util.Logger,f=null,e=[],g=[],h=null,k=!1,l=!1,m=[];return{init:function(){try{window.AudioContext=window.AudioContext||window.webkitAudioContext,f=new AudioContext,d.log("Audio Player initiated.",
d.LogStates.INFO)}catch(a){d.log("Web Audio API not supported by browser",d.LogStates.ERROR)}},loadSound:function(c,d){if(null!==f)if(l)m.push({url:c,cback:d});else{l=!0;var e=new XMLHttpRequest;h=d;e.open("GET",c,!0);e.responseType="arraybuffer";e.onload=function(){f.decodeAudioData(e.response,a,b)};e.send()}else d(-1)},playBuffer:function(a,b){if(null!==f&&0<e.length){g.push(f.createBufferSource());var c=g.length-1;g[c].buffer=e[a];g[c].connect(f.destination);g[c].loop=b;g[c].start(0)}},toggleAudioMute:function(){for(var a=
g.length;a--;)g[a].gain.value=k?1:0,k=!k},fadeVolume:function(a,b,c){var d=.01;b<a.volume&&(d=-d);setTimeout(function(){try{a.volume+=d,a.volume<b&&0<d||a.volume>b&&0>d?com.jasonmayes.jama.multimedia.audio.AudioPlayer.fadeVolume(a,b,c):c()}catch(e){c()}},42)}}}();goog.exportSymbol("com.jasonmayes.jama.multimedia.audio.AudioPlayer",com.jasonmayes.jama.multimedia.audio.AudioPlayer);com.jasonmayes.jama.polyfills={};com.jasonmayes.jama.polyfills.GetUserMedia=function(){navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia}();goog.exportSymbol("com.jasonmayes.jama.polyfills.GetUserMedia",com.jasonmayes.jama.polyfills.GetUserMedia);com.jasonmayes.jama.polyfills.RequestAnimationFrame=function(){window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a){window.setTimeout(a,1E3/30)}}()}();goog.exportSymbol("com.jasonmayes.jama.polyfills.RequestAnimationFrame",com.jasonmayes.jama.polyfills.RequestAnimationFrame);com.jasonmayes.jama.polyfills.VisibilityChange=function(){var a="",b="";"undefined"!==typeof document.hidden?(a="hidden",b="visibilitychange"):"undefined"!==typeof document.mozHidden?(a="mozHidden",b="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(a="msHidden",b="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(a="webkitHidden",b="webkitvisibilitychange");return{pvHidden:a,pvVisibilityChange:b}}();goog.exportSymbol("com.jasonmayes.jama.polyfills.VisibilityChange",com.jasonmayes.jama.polyfills.VisibilityChange);com.jasonmayes.jama.polyfills.WindowUrl=function(){window.URL=window.URL||window.webkitURL||window.mozURL||window.msURL}();goog.exportSymbol("com.jasonmayes.jama.polyfills.WindowUrl",com.jasonmayes.jama.polyfills.WindowUrl);com.jasonmayes.jama.multimedia.video={};
com.jasonmayes.jama.multimedia.video.MediaSampler=function(a,b,c,d,f,e){this.DEBUG_=f;this.MIN_ANALYZE_INTERVAL_=30<c?c:30;this.callback_=d;this.vidSuccessCallback_=function(){};this.lastAnalyzeTime_=0;this.pageIsVisible_=!0;this.canvas_=document.getElementById(a);this.video_=document.getElementById(b);this.ctx_=this.canvas_.getContext("2d");this.imgData_=null;this.webcamStarted_=this.captureMedia_=!1;this.pvHidden_=com.jasonmayes.jama.polyfills.VisibilityChange.pvHidden;this.pvVisibilityChange_=
com.jasonmayes.jama.polyfills.VisibilityChange.pvVisibilityChange;void 0!==e&&(this.selectors_=[],a=!1,void 0!==e.audioSrcSelectId&&(this.audioInputSelect_=document.getElementById(e.audioSrcSelectId),this.audioInputSelect_.addEventListener("change",this.inputDeviceChanged_.bind(this)),this.selectors_.push(this.audioInputSelect_),a=!0),void 0!==e.audioDestSelectId&&(this.audioOutputSelect_=document.getElementById(e.audioDestSelectId),this.audioOutputSelect_.addEventListener("change",this.changeAudioDestination_.bind(this)),
this.selectors_.push(this.audioOutputSelect_),a=!0),void 0!==e.videoSrcSelectId&&(this.videoSelect_=document.getElementById(e.videoSrcSelectId),this.videoSelect_.addEventListener("change",this.inputDeviceChanged_.bind(this)),this.selectors_.push(this.videoSelect_),a=!0),a&&navigator.mediaDevices.enumerateDevices().then(this.gotDevices_.bind(this))["catch"](this.videoStreamError_.bind(this)));document.addEventListener(this.pvVisibilityChange_,function(){this.pageIsVisible_=document[this.pvHidden_]?
!1:!0;this.DEBUG_&&this.logger_.log("Visibility: "+this.pageIsVisible_,this.logger_.LogStates.DEBUG)}.bind(this))};goog.exportSymbol("com.jasonmayes.jama.multimedia.video.MediaSampler",com.jasonmayes.jama.multimedia.video.MediaSampler);com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.logger_=new com.jasonmayes.jama.util.Logger;
com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.changeAudioDestination_=function(){var a=this.audioOutputSelect_.value;"undefined"!==typeof this.video_.sinkId?this.video_.setSinkId(a).then(function(){this.DEBUG_&&this.logger_.log("Success, audio output device attached: "+a,this.logger_.LogStates.DEBUG)})["catch"](function(a){if(this.DEBUG_){var c=a;"SecurityError"===a.name&&(c="You need to use HTTPS for selecting audio output device: "+a);this.logger_.log(c,this.logger_.LogStates.ERROR)}this.audioOutputSelect_.selectedIndex=
0}):this.DEBUG_&&this.logger_.log("Browser does not support output device selection.",this.logger_.LogStates.WARNING)};com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.inputDeviceChanged_=function(){this.video_.pause();var a={};if(this.audioInputSelect_){var b=this.audioInputSelect_.value;a.audio={deviceId:b?{exact:b}:void 0}}this.videoSelect_&&(b=this.videoSelect_.value,a.video={deviceId:b?{exact:b}:void 0});navigator.getUserMedia(a,this.videoStreamSuccess_.bind(this),this.videoStreamError_.bind(this))};
com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.gotDevices_=function(a){var b=this.selectors_.map(function(a){return a.value});this.selectors_.forEach(function(a){for(;a.firstChild;)a.removeChild(a.firstChild)});for(var c=0;c!==a.length;++c){var d=a[c],f=document.createElement("option");f.value=d.deviceId;"audioinput"===d.kind&&this.audioInputSelect_?(f.text=d.label||"microphone "+(this.audioInputSelect_.length+1),this.audioInputSelect_.appendChild(f)):"audiooutput"===d.kind&&this.audioOutputSelect_?
(f.text=d.label||"speaker "+(this.audioOutputSelect_.length+1),this.audioOutputSelect_.appendChild(f)):"videoinput"===d.kind&&this.videoSelect_?(f.text=d.label||"camera "+(this.videoSelect_.length+1),this.videoSelect_.appendChild(f)):this.DEBUG_&&this.logger_.log("Some other kind of source/device: ",this.logger_.LogStates.INFO,d)}this.selectors_.forEach(function(a,c){Array.prototype.slice.call(a.childNodes).some(function(a){return a.value===b[c]})&&(a.value=b[c])})};
com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.sampleVideoStream_=function(){if(this.captureMedia_&&this.webcamStarted_&&Date.now()-this.lastAnalyzeTime_>this.MIN_ANALYZE_INTERVAL_&&this.pageIsVisible_)try{this.canvas_.width=this.video_.offsetWidth,this.canvas_.height=this.video_.offsetHeight,this.ctx_.drawImage(this.video_,0,0,this.video_.offsetWidth,this.video_.offsetHeight),this.imgData_=this.ctx_.getImageData(0,0,this.canvas_.width,this.canvas_.height),this.ctx_.putImageData(this.imgData_,
0,0),this.callback_(),this.lastAnalyzeTime_=Date.now()}catch(a){this.DEBUG_&&this.logger_.log(a,this.logger_.LogStates.DEBUG)}this.captureMedia_&&requestAnimFrame(this.sampleVideoStream_.bind(this))};com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.videoInitPlay_=function(){try{this.video_.play()}catch(a){this.vidSuccessCallback_(a)}this.webcamStarted_=!0;this.vidSuccessCallback_&&this.vidSuccessCallback_()};
com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.videoStreamSuccess_=function(a){this.video_.src=window.URL&&window.URL.createObjectURL(a);this.videoInitPlay_()};com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.videoStreamError_=function(){this.DEBUG_&&this.logger_.log("Video error.",this.logger_.LogStates.ERROR)};
com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.start=function(a,b){this.captureMedia_=!0;this.webcamStarted_=!1;this.vidSuccessCallback_=a;b?(this.video_.src=b,this.videoInitPlay_()):navigator.getUserMedia?void 0!==this.videoSelect_?this.inputDeviceChanged_():navigator.getUserMedia({video:!0},this.videoStreamSuccess_.bind(this),this.videoStreamError_.bind(this)):this.logger_.log("Your browser does not support getUserMedia",this.logger_.LogStates.ERROR);requestAnimFrame(this.sampleVideoStream_.bind(this));
return this.captureMedia_};goog.exportProperty(com.jasonmayes.jama.multimedia.video.MediaSampler.prototype,"start",com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.start);com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.stop=function(a){this.webcamStarted_=this.captureMedia_=!1;this.video_.pause();this.ctx_.clearRect(0,0,this.canvas_.width,this.canvas_.height);a&&a();return this.captureMedia_};
goog.exportProperty(com.jasonmayes.jama.multimedia.video.MediaSampler.prototype,"stop",com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.stop);com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.toggle=function(a){return this.captureMedia_?this.stop(a):this.start(a)};goog.exportProperty(com.jasonmayes.jama.multimedia.video.MediaSampler.prototype,"toggle",com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.toggle);
com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.takeCanvasSnapshot=function(a){return this.canvas_.toDataURL("image/jpeg",a?a:.65)};goog.exportProperty(com.jasonmayes.jama.multimedia.video.MediaSampler.prototype,"takeCanvasSnapshot",com.jasonmayes.jama.multimedia.video.MediaSampler.prototype.takeCanvasSnapshot);com.jasonmayes.jama.util.Objects=function(){return{replaceProperties:function(a,b){for(var c=Object.keys(a),d=0;d<c.length;d++)b.hasOwnProperty(c[d])&&(a[c[d]]=b[c[d]])}}}();goog.exportSymbol("com.jasonmayes.jama.util.Objects",com.jasonmayes.jama.util.Objects);com.jasonmayes.jama.network={};com.jasonmayes.jama.network.ServerCommunicator=function(a){this.options_={debug:!1,server:"//localhost",path:"/",requestType:"POST"};a&&com.jasonmayes.jama.util.Objects.replaceProperties(this.options_,a)};goog.exportSymbol("com.jasonmayes.jama.network.ServerCommunicator",com.jasonmayes.jama.network.ServerCommunicator);com.jasonmayes.jama.network.ServerCommunicator.prototype.logger_=new com.jasonmayes.jama.util.Logger;
com.jasonmayes.jama.network.ServerCommunicator.prototype.sendFormData=function(a,b,c){this.options_.debug&&this.logger_.log("Sending image data to API",this.logger_.LogStates.DEBUG);var d=new XMLHttpRequest;d.onreadystatechange=function(){var a=d.response;if(4===d.readyState)if(200===d.status)this.processApiResponse(JSON.parse(a),b,c);else try{c(JSON.parse(a))}catch(e){c(JSON.parse('{"error": "API did not respond"}'))}}.bind(this);d.ontimeout=function(){c(JSON.parse('{"error": "API request timed out"}'))};
for(var f=new FormData,e=0;e<a.length;e++)f.append(a[e].name,a[e].data);d.timeout=1E4;d.open(this.options_.requestType,this.options_.server+this.options_.path);d.send(f)};goog.exportProperty(com.jasonmayes.jama.network.ServerCommunicator.prototype,"sendFormData",com.jasonmayes.jama.network.ServerCommunicator.prototype.sendFormData);
com.jasonmayes.jama.network.ServerCommunicator.prototype.sendJsonData=function(a,b,c){this.options_.debug&&this.logger_.log("Sending text data to API",this.logger_.LogStates.DEBUG);var d=new XMLHttpRequest;d.onreadystatechange=function(){if(4===d.readyState)if(200===d.status)b(JSON.parse(d.response+""));else try{c(JSON.parse(d.response+""))}catch(a){c(JSON.parse('{"error": "API did not respond"}'))}}.bind(this);d.ontimeout=function(){c(JSON.parse('{"error": "API request timed out"}'))};d.timeout=
1E4;d.open(this.options_.requestType,this.options_.server+this.options_.path);d.setRequestHeader("Content-type","application/json");d.send(a)};goog.exportProperty(com.jasonmayes.jama.network.ServerCommunicator.prototype,"sendJsonData",com.jasonmayes.jama.network.ServerCommunicator.prototype.sendJsonData);
com.jasonmayes.jama.network.ServerCommunicator.prototype.processApiResponse=function(a,b,c){this.options_.debug&&this.logger_.log("Processing API responses",this.logger_.LogStates.DEBUG,a);a.labels?b(a):a.error&&(this.options_.debug&&this.logger_.log("Error in results",this.logger_.LogStates.ERROR,a.error.message),c(a))};goog.exportProperty(com.jasonmayes.jama.network.ServerCommunicator.prototype,"processApiResponse",com.jasonmayes.jama.network.ServerCommunicator.prototype.processApiResponse);com.jasonmayes.jama.JaMa=function(){};goog.exportSymbol("com.jasonmayes.jama.JaMa",com.jasonmayes.jama.JaMa);
