// This file was autogenerated by calcdeps.py
goog.addDependency("../../../../src/com/jasonmayes/ctt/CTT.js", ['com.jasonmayes.ctt.CTT'], ['com.jasonmayes.ctt.multimedia.audio.AudioPlayer', 'com.jasonmayes.ctt.multimedia.video.MediaSampler', 'com.jasonmayes.ctt.network.ServerCommunicator', 'com.jasonmayes.ctt.polyfills.GetUserMedia', 'com.jasonmayes.ctt.polyfills.RequestAnimationFrame', 'com.jasonmayes.ctt.polyfills.VisibilityChange', 'com.jasonmayes.ctt.polyfills.WindowUrl', 'com.jasonmayes.ctt.util.Logger', 'com.jasonmayes.ctt.util.Objects', 'com.jasonmayes.ctt.classification.KNN', 'com.jasonmayes.ctt.structs.Tuple', 'com.jasonmayes.ctt.structs.LabelledTuple']);
goog.addDependency("../../../../src/com/jasonmayes/ctt/multimedia/audio/AudioPlayer.js", ['com.jasonmayes.ctt.multimedia.audio.AudioPlayer'], ['com.jasonmayes.ctt.util.Logger']);
goog.addDependency("../../../../src/com/jasonmayes/ctt/multimedia/video/MediaSampler.js", ['com.jasonmayes.ctt.multimedia.video.MediaSampler'], ['com.jasonmayes.ctt.polyfills.GetUserMedia', 'com.jasonmayes.ctt.polyfills.RequestAnimationFrame', 'com.jasonmayes.ctt.polyfills.VisibilityChange', 'com.jasonmayes.ctt.polyfills.WindowUrl', 'com.jasonmayes.ctt.util.Logger']);
goog.addDependency("../../../../src/com/jasonmayes/ctt/network/ServerCommunicator.js", ['com.jasonmayes.ctt.network.ServerCommunicator'], ['com.jasonmayes.ctt.util.Logger', 'com.jasonmayes.ctt.util.Objects']);
goog.addDependency("../../../../src/com/jasonmayes/ctt/polyfills/GetUserMedia.js", ['com.jasonmayes.ctt.polyfills.GetUserMedia'], []);
goog.addDependency("../../../../src/com/jasonmayes/ctt/polyfills/RequestAnimationFrame.js", ['com.jasonmayes.ctt.polyfills.RequestAnimationFrame'], []);
goog.addDependency("../../../../src/com/jasonmayes/ctt/polyfills/VisiblityChange.js", ['com.jasonmayes.ctt.polyfills.VisibilityChange'], []);
goog.addDependency("../../../../src/com/jasonmayes/ctt/polyfills/WindowUrl.js", ['com.jasonmayes.ctt.polyfills.WindowUrl'], []);
goog.addDependency("../../../../src/com/jasonmayes/ctt/util/Logger.js", ['com.jasonmayes.ctt.util.Logger'], []);
goog.addDependency("../../../../src/com/jasonmayes/ctt/util/Objects.js", ['com.jasonmayes.ctt.util.Objects'], []);
goog.addDependency("../../../../src/com/jasonmayes/ctt/structs/Tuple.js", ['com.jasonmayes.ctt.structs.Tuple'], []);
goog.addDependency("../../../../src/com/jasonmayes/ctt/structs/LabelledTuple.js", ['com.jasonmayes.ctt.structs.LabelledTuple'], ['com.jasonmayes.ctt.structs.Tuple']);
goog.addDependency("../../../../src/com/jasonmayes/ctt/classification/KNN.js", ['com.jasonmayes.ctt.classification.KNN'], ['com.jasonmayes.ctt.structs.Tuple', 'com.jasonmayes.ctt.structs.LabelledTuple', 'com.jasonmayes.ctt.util.Logger']);
